baseURL = "https://trusting-blackwell-a10d33.netlify.com/"
languageCode = "en-us"
theme = "hyde"
title = "My New Hugo Site"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""
